// export const products = [
//   {
//     id: "1",
//     name: "Bamboo Tan",
//     currency: "USD",
//     price: 199,
//     flag: "new",
//     imageUrl:
//       "https://images.unsplash.com/photo-1602024242516-fbc9d4fda4b6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80",
//     rating: 1,
//     ratingCount: 1,
//     description:
//       "With a sleek design and a captivating essence, this is a modern Classic made for every occasion.",
//   },
//   {
//     id: "2",
//     name: "Iconic Turquoise",
//     currency: "USD",
//     price: 199,
//     salePrice: 0,
//     flag: "on-sale",
//     imageUrl:
//       "https://images.unsplash.com/photo-1509941943102-10c232535736?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80",
//     rating: 2,
//     ratingCount: 12,
//     description:
//       "With a sleek design and a captivating essence, this is a modern Classic made for every occasion.",
//   },
//   {
//     id: "3",
//     name: "Marble Leather",
//     currency: "USD",
//     price: 199,
//     imageUrl:
//       "https://images.unsplash.com/photo-1564594985645-4427056e22e2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80",
//     rating: 3,
//     ratingCount: 12,
//     description:
//       "With a sleek design and a captivating essence, this is a modern Classic made for every occasion.",
//   },
//   {
//     id: "4",
//     name: "Silve wolf",
//     currency: "GBP",
//     price: 199,
//     imageUrl:
//       "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=680&q=80",
//     rating: 4.5,
//     ratingCount: 1,
//     description:
//       "With a sleek design and a captivating essence, this is a modern Classic made for every occasion.",
//   },
// ];

export const products = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 8,
    spoonacularScore: 87.0,
    healthScore: 45.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 754.48,
    extendedIngredients: [
      {
        id: 98840,
        aisle: "Produce",
        image: "broccolini.jpg",
        consistency: "solid",
        name: "broccolini",
        nameClean: "broccolini",
        original: "1 bunch of Broccolini",
        originalString: "1 bunch of Broccolini",
        originalName: "Broccolini",
        amount: 1.0,
        unit: "bunch",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1.0,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
    ],
    id: 657167,
    title: "Prosciutto Wrapped Broccolini With Basil Crisps",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/7435XMJZ/prosciutto-wrapped-broccolini-with-basil-crisps",
    image: "https://spoonacular.com/recipeImages/657167-556x370.jpg",
    imageType: "jpg",
    summary: `If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Prosciutto Wrapped Broccolini With Basil Crisps might be an awesome <b>gluten free, dairy free, paleolithic, and primal</b> recipe to try. For <b>$7.54 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>146g of protein</b>, <b>21g of fat</b>, and a total of <b>878 calories</b>. This recipe serves 4. 8 people have tried and liked this recipe. If you have olive oil, basil, salt and pepper, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. With a spoonacular <b>score of 87%</b>, this dish is tremendous. <a href="https://spoonacular.com/recipes/prosciutto-wrapped-shrimp-with-mozzarella-and-basil-149340">Prosciutto-Wrapped Shrimp with Mozzarellan and Basil</a>, <a href="https://spoonacular.com/recipes/pass-the-prosciutto-prosciutto-wrapped-pear-with-parmesan-551304">pass the prosciutto – prosciutto wrapped pear with parmesan</a>, and <a href="https://spoonacular.com/recipes/caramelized-onion-prosciutto-and-broccolini-crustless-quiche-592959">Caramelized Onion, Prosciutto and Broccolini Crustless Quiche</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "fodmap friendly",
    ],
    occasions: [],
    instructions:
      "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil. Add a generous amount of salt. Blanch the broccolini for 30 seconds, remove, then submerge into the ice bath. When the broccolini is fully cooled, drain and pat dry with a kitchen towel.\nReduce the balsamic vinegar over medium heat until it becomes 1/4 cup of sticky syrup. Set aside.\nDrop a small handful of basil leaves into the oil. Shield yourself from potential splatter. It only takes one second for the leaves to pop. Immediately fish them from the oil with a strainer and place onto a towel-lined plate. The leaves should become crisp and translucent, but not darkened or it will be bitter.\nHeat up the grill and coat generously with olive oil. Grill the broccolini until slightly charred and softened. Season with salt and pepper.\nWrap the broccolini with prosciutto. Place onto serving platter, drizzle with some extra virgin olive oil and the balsamic reduction.\nGarnish with basil crisps when ready to serve.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Prepare an ice bath. Trim the bottom tip off the broccolini. Bring a large pot of water to a rolling boil.",
            ingredients: [
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-wrapped-broccolini-with-basil-crisps-657167",
  },
];

export type ElementType<T extends ReadonlyArray<unknown>> =
  T extends ReadonlyArray<infer ElementType> ? ElementType : never;

export type Product = ElementType<typeof products>;
